import guassConfig from './public/guass/config'
import assetConfig from './public/asset/config'
import homeConfig from './public/home/config'
import newTrandingFairConfig from './public/new-tranding-fair/config'
import ordinalsConfig from './public/ordinals/config'
import weekendConfig from './public/weekend/config'
import priceDetailConfig from './public/price-detail/config'
import priceDetailWebsiteConfig from './public/price-detail-website/config'
import converterConfig from './public/converter/config'
import howtobuyConfig from './public/howtobuy/config'
import price_prediction from './public/price_prediction/config'
import priceConfig from './public/price/config'
import coin_details from './public/coin_details/config'
import price_sg from './public/price_sg/config'
import price_tr from './public/price_tr/config'
import price_details_v2 from './public/price_details_v2/config'
import bahamas_config from './public/bahamas/config'
import converter_v2 from './public/converter_v2/config'


export default converter_v2